### ISSUE TITLE
Running :lua require("toolwindow").open_window("todo", nil) opens diagnostics

### ISSUE THREAD

**Issue by beauwilliams** [EthanJWright/toolwindow.nvim#8]
I'm not sure what I am doing wrong. I have todo-comments installed and working. But its opening diagnostics each time.

**Comment by EthanJWright** [comment]
Let me try to reproduce it shortly, perhaps an API changed

**Comment by EthanJWright** [comment]
@beauwilliams I believe there was a change to the trouble API for passing specific providers, it seems to be working in my environment after a fix that I pushed. Let me know if it's working for you after updating now.

**Comment by beauwilliams** [comment]
@EthanJWright I've pulled the latest update and looks like its working for me now, thank you 👍
